/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/greencurdoroy_wood.glb --transform 
Files: public/models/greencurdoroy_wood.glb [211.39MB] > C:\Users\jadel\OneDrive\Projects\3D_personalization\couch-personalisation\greencurdoroy_wood-transformed.glb [2.02MB] (99%)
*/

import { useGLTF } from '@react-three/drei'
import { Color } from 'three'
const base = import.meta.env.BASE_URL

export default function CurdoroyModel({color, feetType, ...props}) {
  const { nodes, materials } = useGLTF(base + 'models/greencurdoroy_wood-transformed.glb')
  return (
    <group {...props} dispose={null} rotation={[0,3.6,0]}>
      <mesh geometry={nodes.Mesh004.geometry}>
        {feetType === 'wood' && <meshStandardMaterial 
          {...materials.M_Piedini}
          color={'#965757'}
          roughness={0.7}
        />}
        {feetType === 'chrome' && <meshStandardMaterial 
          roughness={0}
          metalness={1}          
        />}
      </mesh>
      
      <mesh geometry={nodes.Mesh004_1.geometry}>
        <meshStandardMaterial 
          {...materials.M_TessutoDivano} 
          map={null}
          color={new Color(color).convertSRGBToLinear()}                  
        />
      </mesh>
    </group>
  )
}

useGLTF.preload(base + 'models/greencurdoroy_wood-transformed.glb')
