/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/redleather_wood.glb --transform 
Files: public/models/redleather_wood.glb [155.29MB] > C:\Users\jadel\OneDrive\Projects\3D_personalization\couch-personalisation\redleather_wood-transformed.glb [1.56MB] (99%)
*/

import { useGLTF } from '@react-three/drei'
import { Color } from 'three'

export default function LeatherModel({color, feetType, ...props}) {
  const { nodes, materials } = useGLTF('../public/models/redleather_wood-transformed.glb')
  return (
    <group {...props} dispose={null} rotation={[0,3.6,0]}>
      <mesh geometry={nodes.Mesh004.geometry}>
        {feetType === 'wood' && <meshStandardMaterial 
          {...materials.M_Piedini}           
        />}
        {feetType === 'chrome' && <meshStandardMaterial 
          roughness={0}
          metalness={1}          
        />}
      </mesh>
      
      <mesh geometry={nodes.Mesh004_1.geometry}>
        <meshStandardMaterial 
          {...materials.M_TessutoDivano} 
          map={null}
          color={new Color(color).convertSRGBToLinear()}                 
        />
      </mesh>
    </group>
  )
}

useGLTF.preload('../public/models/redleather_wood-transformed.glb')
