/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/greenwaffle_wood.glb --transform 
Files: public/models/greenwaffle_wood.glb [214.83MB] > C:\Users\jadel\OneDrive\Projects\3D_personalization\couch-personalisation\greenwaffle_wood-transformed.glb [1.79MB] (99%)
*/

import { useGLTF } from '@react-three/drei'
import { Color } from 'three'
import * as THREE from 'three'

export default function WaffleModel({color, feetType, ...props}) {
  const { nodes, materials } = useGLTF('../public/models/greenwaffle_wood-transformed.glb')

  const mat = materials.M_TessutoDivano;
  [mat.normalMap, mat.roughnessMap, mat.aoMap].forEach((tex) => {
    if (tex) {
      tex.wrapS = THREE.RepeatWrapping
      tex.wrapT = THREE.RepeatWrapping
      tex.repeat.set(4, 4)
    }
  })

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh004.geometry}>
        {feetType === 'wood' && <meshStandardMaterial 
          {...materials.M_Piedini}
          color={'#965757'}
          roughness={0.7}    
        />}
        {feetType === 'chrome' && <meshStandardMaterial 
          roughness={0}
          metalness={1}          
        />}
      </mesh>
      
      <mesh geometry={nodes.Mesh004_1.geometry}>
        <meshStandardMaterial 
          {...materials.M_TessutoDivano} 
          map={null}
          color={new Color(color).convertSRGBToLinear()}
          roughness={1}             
        />
      </mesh>
    </group>
  )
}

useGLTF.preload('../public/models/greenwaffle_wood-transformed.glb')
